import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import { useSession, getSession, signIn, signOut } from 'next-auth/react';
import Layout from '../components/Layout/Layout';

const Home = () => {
	const { data: session } = useSession();

	const [isLoading, setIsLoading] = useState(true);
	const router = useRouter();

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>{session ? `Hi ${session.user.FullName}` : 'Hi there, stranger!'}</Layout>
		</>
	);
};

export default Home;
